/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as V7RouteImport } from './routes/v7'
import { Route as V6RouteImport } from './routes/v6'
import { Route as V4RouteImport } from './routes/v4'
import { Route as IndexRouteImport } from './routes/index'

const V7Route = V7RouteImport.update({
  id: '/v7',
  path: '/v7',
  getParentRoute: () => rootRouteImport,
} as any)
const V6Route = V6RouteImport.update({
  id: '/v6',
  path: '/v6',
  getParentRoute: () => rootRouteImport,
} as any)
const V4Route = V4RouteImport.update({
  id: '/v4',
  path: '/v4',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/v4': typeof V4Route
  '/v6': typeof V6Route
  '/v7': typeof V7Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/v4': typeof V4Route
  '/v6': typeof V6Route
  '/v7': typeof V7Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/v4': typeof V4Route
  '/v6': typeof V6Route
  '/v7': typeof V7Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/v4' | '/v6' | '/v7'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/v4' | '/v6' | '/v7'
  id: '__root__' | '/' | '/v4' | '/v6' | '/v7'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  V4Route: typeof V4Route
  V6Route: typeof V6Route
  V7Route: typeof V7Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/v7': {
      id: '/v7'
      path: '/v7'
      fullPath: '/v7'
      preLoaderRoute: typeof V7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v6': {
      id: '/v6'
      path: '/v6'
      fullPath: '/v6'
      preLoaderRoute: typeof V6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v4': {
      id: '/v4'
      path: '/v4'
      fullPath: '/v4'
      preLoaderRoute: typeof V4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  V4Route: V4Route,
  V6Route: V6Route,
  V7Route: V7Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
